version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip3 install aws-sam-cli

  build:
    commands:
      # Use AWS SAM to build and package the application by using AWS CloudFormation
      - sam build --debug
      - sam package --template-file template.yaml --s3-bucket $S3_BUCKET --output-template-file packaged.yaml --force-upload

artifacts:
  files:
    - packaged.yaml
