version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip3 install aws-sam-cli

  build:
    commands:
      # Use AWS SAM to build and package the application by using AWS CloudFormation
      - sam build --debug
      - sam package --debug --template-file .aws-sam/build/template.yaml --s3-bucket $S3_BUCKET --output-template-file sampackaged.yaml --force-upload
  post_build:
    commands:
      # publishing to SAR
#      - echo GIT_REPO=$GIT_REPO
#      - echo CODEBUILD_RESOLVED_SOURCE_VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION
#      - env | sort
#      - curl -s https://api.github.com/repos/BIBSYSDEV/$GIT_REPO/tags
#      - export APPLICATION_VERSION=$(curl -s https://api.github.com/repos/BIBSYSDEV/$GIT_REPO/tags | jq '.[]  | select(.commit.sha == "$CODEBUILD_RESOLVED_SOURCE_VERSION" ) | .name' | head -1)
      - APPLICATION_VERSION=$(curl -s  https://api.github.com/repos/BIBSYSDEV/$GIT_REPO/tags | jq '.[].name' | sort -r | head -1)
      - echo GIT_REPO=$GIT_REPO APPLICATION_VERSION=$APPLICATION_VERSION
      - envsubst < sampackaged.yaml > sampackaged_subst.yaml
      - sam publish  --semantic-version $APPLICATION_VERSION  --template sampackaged_subst.yaml
artifacts:
  files:
    - sampackaged.yaml
