version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip3 install aws-sam-cli

  build:
    commands:
      # Use AWS SAM to build and package the application by using AWS CloudFormation
      - sam build --debug
      - sam package --debug --template-file .aws-sam/build/template.yaml --s3-bucket $S3_BUCKET --output-template-file sampackaged.yaml --force-upload
  post_build:
    commands:
      # publishing to SAR
#      - sam publish --template sampackaged.yaml
      - env | sort
      - curl https://api.github.com/repos/BIBSYSDEV/$GIT_REPO/tags | jq '.[]  | select(.commit.sha == $CODEBUILD_RESOLVED_SOURCE_VERSION ) | .name'
      - echo APPLICATION_VERSION=$APPLICATION_VERSION
      - sam publish  --semantic-version $APPLICATION_VERSION  --template sampackaged.yaml
artifacts:
  files:
    - sampackaged.yaml
