AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Name: echo-event
    Description: Echos incoming events
    Author: Unit
    ReadmeUrl: README.md
    HomePageUrl: https://github.com/BIBSYSDEV/echo-event
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/BIBSYSDEV/echo-event


Parameters:

  GitHubRepo:
    Type: String
  GitHubBranch:
    Type: String

Resources:

  EchoEvent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: app.handler
      Runtime: python3.7
      Tags:
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch

Outputs:
  LambdaArn:
    Description: 'ARN for lambda function'
    Value: !GetAtt EchoEvent.Arn
    Export:
      Name: !Sub '${AWS::StackName}-lambdaArn'