AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  GitHubRepo:
    Type: String
  CodeDeployRole:
    Type: String
    Description: IAM role to allow AWS CodeDeploy to manage deployment of AWS Lambda functions
  GitHubBranch:
    Type: String

Resources:

  EchoEvent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: app.handler
      Runtime: python3.7
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /echo-event/{id}
            Method: GET
      Tags:
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch

Outputs:
  LambdaArn:
    Description: 'ARN for lambda function'
    Value: !GetAtt EchoEvent.Arn
    Export:
      Name: !Sub 'lambda-${GitHubRepo}-${GitHubBranch}'