AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  GitHubRepo:
    Type: String
  CodeDeployRole:
    Type: String
    Description: IAM role to allow AWS CodeDeploy to manage deployment of AWS Lambda functions
  GitHubBranch:
    Type: String
  ApiName:
    Type: String



Resources:

  EchoEventApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub '${ApiName}'
      StageName: prod



  EchoEvent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: app.handler
      Runtime: python3.7
      Events:
        PostEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EchoEventApi
            Path: /echo-event/{id}
            Method: GET
      Tags:
        GitHubRepo: !Ref GitHubRepo
        GitHubBranch: !Ref GitHubBranch


Outputs:
  APIGatewayRef:
    Description: 'API-Gateway to be used for   this lambda'
    Value: !Ref EchoEventApi
    Export:
      Name: !Sub 'api-gateway-${GitHubRepo}-${GitHubBranch}'