AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  ApiDomain:
    Type: String

Resources:

  EchoEventApi:
    Type: AWS::Serverless::Api
    DependsOn: EchoEvent
    Properties:
      StageName: Prod

  EchoEvent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: app.handler
      Runtime: python3.7
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /{identifier}
            Method: GET
            RestApiId: !Ref EchoEventApi

  EchoEventBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    DependsOn: EchoEventApi
    Properties:
      BasePath: echo-event
      DomainName: !Ref ApiDomain
      RestApiId: !Ref EchoEventApi
      Stage: Prod