AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Name: echo-event
    Description: Echos incoming events
    Author: Unit
    ReadmeUrl: README.md
    HomePageUrl: https://github.com/BIBSYSDEV/echo-event
    SemanticVersion: 0.0.2
    SourceCodeUrl: https://github.com/BIBSYSDEV/echo-event


Parameters:

Resources:

  EchoEvent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: app.handler
      Runtime: python3.7
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: GET

#Outputs:
#  LambdaArn:
#    Description: 'ARN for lambda function'
#    Value: !GetAtt EchoEvent.Arn
#    Export:
#      Name: !Sub '${AWS::StackName}-lambdaArn'