AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31


Metadata:
  AWS::ServerlessRepo::Application:
    Name: echo-event
    Description: Echos incoming events
    Author: Unit
    ReadmeUrl: README.md
    HomePageUrl: https://github.com/BIBSYSDEV/echo-event
    SemanticVersion: 0.1.0
    SourceCodeUrl: https://github.com/BIBSYSDEV/echo-event

Resources:

  EchoGetEvent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: app.handler
      Runtime: python3.7
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /echo
            Method: GET

  EchoPutEvent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: app.handler
      Runtime: python3.7
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /echo/{identifier}
            Method: PUT


  AnotherEchoPutEvent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: app.handler
      Runtime: python3.7
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /another
            Method: PUT
