AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Name: EchoEvent
    Description: Sample project for deploy to SAR
    Author: Unit
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    Labels: ['${CODEBUILD_RESOLVED_SOURCE_VERSION}', '${GIT_REPO}, ${BUILD_TIMESTAMP}']

Resources:

  EchoEventApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"

  EchoPutEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: app.handler
      Runtime: python3.8
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /
            Method: PUT
            RestApiId: !Ref EchoEventApi
  EchoPostEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: app.handler
      Runtime: python3.8
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /
            Method: POST
            RestApiId: !Ref EchoEventApi
  EchoGetEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: app.handler
      Runtime: python3.8
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref EchoEventApi





