AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31


Metadata:
  AWS::ServerlessRepo::Application:
    Name: echo-event
    Description: Echos incoming events
    Author: Unit
    ReadmeUrl: README.md
    HomePageUrl: https://github.com/BIBSYSDEV/echo-event
    SemanticVersion: 0.1.1
    SourceCodeUrl: https://github.com/BIBSYSDEV/echo-event

Resources:




  EchoGetEvent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: app.handler
      Runtime: python3.7
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /{identifier}
            Method: GET

  EchoGet2Event:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: app.handler
      Runtime: python3.7
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /other
            Method: GET


  EchoPutEvent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: app.handler
      Runtime: python3.7
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /{identifier}
            Method: PUT


  EchoPostEvent:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: app.handler
      Runtime: python3.7
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /
            Method: POST


